# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    cache:
        pools:
            cache.rate_limiter:
                adapter: cache.adapter.filesystem

    # Rate Limiter Configuration
    rate_limiter:
        url_creation:
            policy: 'sliding_window'
            limit: '%env(int:RATE_LIMITER_URL_CREATION_LIMIT)%'
            interval: '%env(int:RATE_LIMITER_URL_CREATION_INTERVAL_SECONDS)% seconds'
            cache_pool: cache.rate_limiter

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
